package interfacevisual;

import java.awt.Color;
import java.lang.ref.Cleaner;
import javax.swing.JOptionPane;
import javax.swing.plaf.SliderUI;

/**
 *
 * @author vitor
 */
public class CadastroFuncionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName());

    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
    }
    public void dados(){
        try {
            String funcionario = "";
            String turnoSelect = "";
            String beneficios = "";
            String nivelFinal = "";
            String setorSelect = cbSetor.getSelectedItem().toString();
             //pega o nome do funcionario
            if (txfNomeFuncionario.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Digite o nome!");
                    return;
            }else{
                funcionario = txfNomeFuncionario.getText();
            }
            //pega o item do combo box
            //pega as seleções da checkbox
            if(ckbValeAlimento.isSelected())
                beneficios+= "- Vale Alimentação\n";
            if(ckbPlanoSaude.isSelected())
                beneficios+= "- Plano de Saúde\n";
            if(ckbValeTransporte.isSelected())
                beneficios+= "- Vale Trasnporte\n";
            if(ckbHomeOffice.isSelected())
                beneficios+= "- Home Office\n";
            if (beneficios.equals("")) {
                beneficios = "Nenhum beneficio atribuido!";
            }

            if(jrbManha.isSelected()){
                turnoSelect = "Manhã";
            }else if(jrbTarde.isSelected()){
                turnoSelect = "Tarde";
            }else if(jrbNoite.isSelected()){
                turnoSelect = "Noite";
            }else{
                JOptionPane.showMessageDialog(null, "Selecione o Turno");
            }

            int nivel = sldNivel.getValue();
            if (nivel > 0 && nivel <= 3) {
                nivelFinal = "\nExperiencia:\nNivel:"+nivel+" | Junior";
            } else if (nivel > 3 && nivel <= 6) {
                nivelFinal = "\nExperiencia:\nNivel:"+nivel+" | Pleno";
            } else if (nivel > 6 && nivel <= 10) {
                nivelFinal = "\nExperiencia:\nNivel:"+nivel+" | Sênior";
            } else {
                JOptionPane.showMessageDialog(null, "Nivel de Experiencia nao selecionado!");
            }
            System.out.println("Funcionario:\n"+funcionario);

            System.out.println("\nSetor:\n"+setorSelect);

            System.out.println("\nTurno:\n"+turnoSelect);

            System.out.println("\nBeneficios:\n"+beneficios);

            System.out.println(nivelFinal);

            System.out.println("------------------------------");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar funcionario, tente mais tarde!");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTurno = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfNomeFuncionario = new javax.swing.JTextField();
        cbSetor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jrbNoite = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jrbManha = new javax.swing.JRadioButton();
        jrbTarde = new javax.swing.JRadioButton();
        ckbHomeOffice = new javax.swing.JCheckBox();
        ckbValeAlimento = new javax.swing.JCheckBox();
        ckbPlanoSaude = new javax.swing.JCheckBox();
        ckbValeTransporte = new javax.swing.JCheckBox();
        sldNivel = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        lblExp = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Funcionário");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Cadastro de Funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 29, 372, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/crachagreen.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Setor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        txfNomeFuncionario.addActionListener(this::txfNomeFuncionarioActionPerformed);
        jPanel1.add(txfNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 300, -1));

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "RH", "Financeiro", "Administrativo" }));
        cbSetor.addActionListener(this::cbSetorActionPerformed);
        jPanel1.add(cbSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 300, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/saveGreen.png"))); // NOI18N
        jButton1.setText("Salvar Cadastro");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 415, 169, 42));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 230, 208));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("Nome do Funcionário");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("Nivel de Experiência");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, -1, -1));

        bgTurno.add(jrbNoite);
        jrbNoite.setForeground(new java.awt.Color(51, 204, 0));
        jrbNoite.setText("Noite");
        jPanel1.add(jrbNoite, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Turno de Trabalho");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, 20));

        bgTurno.add(jrbManha);
        jrbManha.setForeground(new java.awt.Color(51, 204, 0));
        jrbManha.setText("Manhã");
        jPanel1.add(jrbManha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, 30));

        bgTurno.add(jrbTarde);
        jrbTarde.setForeground(new java.awt.Color(51, 204, 0));
        jrbTarde.setText("Tarde");
        jPanel1.add(jrbTarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, 30));

        ckbHomeOffice.setForeground(new java.awt.Color(51, 204, 0));
        ckbHomeOffice.setText("Home Office");
        jPanel1.add(ckbHomeOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        ckbValeAlimento.setForeground(new java.awt.Color(51, 204, 0));
        ckbValeAlimento.setText("Vale Alimentação");
        jPanel1.add(ckbValeAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        ckbPlanoSaude.setForeground(new java.awt.Color(51, 204, 0));
        ckbPlanoSaude.setText("Plano de Saúde");
        ckbPlanoSaude.addActionListener(this::ckbPlanoSaudeActionPerformed);
        jPanel1.add(ckbPlanoSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        ckbValeTransporte.setForeground(new java.awt.Color(51, 204, 0));
        ckbValeTransporte.setText("Vale Trasnporte");
        jPanel1.add(ckbValeTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        sldNivel.setForeground(new java.awt.Color(51, 204, 0));
        sldNivel.setMajorTickSpacing(2);
        sldNivel.setMaximum(10);
        sldNivel.setPaintLabels(true);
        sldNivel.setPaintTicks(true);
        sldNivel.setValue(5);
        sldNivel.addChangeListener(this::sldNivelStateChanged);
        jPanel1.add(sldNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Benefícios Desejados");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblExp.setForeground(new java.awt.Color(51, 204, 0));
        lblExp.setText("Experiência:");
        jPanel1.add(lblExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));

        jSeparator2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 210, 208));

        jSeparator3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 98, 670, 90));

        jSeparator4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 208));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomeFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dados();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSetorActionPerformed

    private void ckbPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbPlanoSaudeActionPerformed

    private void sldNivelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldNivelStateChanged
        //pega o valor:
        int nivelAtual = sldNivel.getValue();
        //Atualiza a label:
        lblExp.setText(String.valueOf("Experiência: "+nivelAtual));
        if (nivelAtual > 0 && nivelAtual <= 3) {
            lblExp.setForeground(Color.red);
        }else if(nivelAtual > 3 && nivelAtual <= 6){
            lblExp.setForeground(new java.awt.Color(255,102,0));
        }else if(nivelAtual > 6 && nivelAtual <= 10){
            lblExp.setForeground(new java.awt.Color(255,204,0));
        }else{
            lblExp.setForeground(Color.red);
        }
        
    }//GEN-LAST:event_sldNivelStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFuncionarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTurno;
    private javax.swing.JComboBox<String> cbSetor;
    private javax.swing.JCheckBox ckbHomeOffice;
    private javax.swing.JCheckBox ckbPlanoSaude;
    private javax.swing.JCheckBox ckbValeAlimento;
    private javax.swing.JCheckBox ckbValeTransporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JRadioButton jrbManha;
    private javax.swing.JRadioButton jrbNoite;
    private javax.swing.JRadioButton jrbTarde;
    private javax.swing.JLabel lblExp;
    private javax.swing.JSlider sldNivel;
    private javax.swing.JTextField txfNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
