package interfacevisual;

import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class CadastroFuncionarios extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFuncionarios.class.getName());

    /**
     * Creates new form CadastroFuncionarios
     */
    public CadastroFuncionarios() {
        initComponents();
    }
    public void dados(){
        String funcionario = txfNomeFuncionario.getText();
        System.out.println("Funcionario:\n"+funcionario);
        String setorSelect = cbSetor.getSelectedItem().toString();
        System.out.println("\nSetor:\n"+setorSelect);
        
        String beneficios = "";
        if(ckbValeAlimento.isSelected())
            beneficios+= "- Vale Alimentação\n";
        if(ckbPlanoSaude.isSelected())
            beneficios+= "- Plano de Saúde\n";
        if(ckbValeTransporte.isSelected())
            beneficios+= "- Vale Trasnporte\n";
        if(ckbHomeOffice.isSelected())
            beneficios+= "- Home Office\n";
        else{
            beneficios = "Nenhum beneficio atribuido!";
        }
        
        String turnoSelect = "";
        if(jrbManha.isSelected()){
            turnoSelect = "Manhã";
        }else if(jrbTarde.isSelected()){
            turnoSelect = "Tarde";
        }else if(jrbNoite.isSelected()){
            turnoSelect = "Noite";
        }else{
            JOptionPane.showMessageDialog(null, "Selecione o Turno");
        }
        System.out.println("\nTurno:\n"+turnoSelect);
        
        System.out.println("\nBeneficios:\n"+beneficios);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgTurno = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfNomeFuncionario = new javax.swing.JTextField();
        cbSetor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jrbNoite = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jrbManha = new javax.swing.JRadioButton();
        jrbTarde = new javax.swing.JRadioButton();
        ckbHomeOffice = new javax.swing.JCheckBox();
        ckbValeAlimento = new javax.swing.JCheckBox();
        ckbPlanoSaude = new javax.swing.JCheckBox();
        ckbValeTransporte = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Funcionário");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Cadastro de Funcionário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 29, 372, 51));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/crachagreen.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 110, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 204, 0));
        jLabel3.setText("Setor");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        txfNomeFuncionario.addActionListener(this::txfNomeFuncionarioActionPerformed);
        jPanel1.add(txfNomeFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, 300, -1));

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TI", "RH", "Financeiro", "Administrativo" }));
        cbSetor.addActionListener(this::cbSetorActionPerformed);
        jPanel1.add(cbSetor, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 156, 310, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Salvar Cadastro");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 415, 169, 42));

        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 202, 208));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("Nome do Funcionário");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 118, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 204, 0));
        jLabel6.setText("Benefícios Desejados");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        bgTurno.add(jrbNoite);
        jrbNoite.setForeground(new java.awt.Color(51, 204, 0));
        jrbNoite.setText("Noite");
        jPanel1.add(jrbNoite, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Turno de Trabalho");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, 20));

        bgTurno.add(jrbManha);
        jrbManha.setForeground(new java.awt.Color(51, 204, 0));
        jrbManha.setText("Manhã");
        jPanel1.add(jrbManha, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 30));

        bgTurno.add(jrbTarde);
        jrbTarde.setForeground(new java.awt.Color(51, 204, 0));
        jrbTarde.setText("Tarde");
        jPanel1.add(jrbTarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 30));

        ckbHomeOffice.setForeground(new java.awt.Color(51, 204, 0));
        ckbHomeOffice.setText("Home Office");
        jPanel1.add(ckbHomeOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        ckbValeAlimento.setForeground(new java.awt.Color(51, 204, 0));
        ckbValeAlimento.setText("Vale Alimentação");
        jPanel1.add(ckbValeAlimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        ckbPlanoSaude.setForeground(new java.awt.Color(51, 204, 0));
        ckbPlanoSaude.setText("Plano de Saúde");
        ckbPlanoSaude.addActionListener(this::ckbPlanoSaudeActionPerformed);
        jPanel1.add(ckbPlanoSaude, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        ckbValeTransporte.setForeground(new java.awt.Color(51, 204, 0));
        ckbValeTransporte.setText("Vale Trasnporte");
        jPanel1.add(ckbValeTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomeFuncionarioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dados();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbSetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSetorActionPerformed

    private void ckbPlanoSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbPlanoSaudeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ckbPlanoSaudeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFuncionarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTurno;
    private javax.swing.JComboBox<String> cbSetor;
    private javax.swing.JCheckBox ckbHomeOffice;
    private javax.swing.JCheckBox ckbPlanoSaude;
    private javax.swing.JCheckBox ckbValeAlimento;
    private javax.swing.JCheckBox ckbValeTransporte;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton jrbManha;
    private javax.swing.JRadioButton jrbNoite;
    private javax.swing.JRadioButton jrbTarde;
    private javax.swing.JTextField txfNomeFuncionario;
    // End of variables declaration//GEN-END:variables
}
