/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacevisual;

/**
 *
 * @author 1094260
 */
public class MenuInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuInicial.class.getName());

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jbPlaneta = new javax.swing.JButton();
        jbCalculadora = new javax.swing.JButton();
        jbTriangulo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-convidado-masculino-100.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 100, 100));

        jbPlaneta.setBackground(new java.awt.Color(0, 0, 0));
        jbPlaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons8-gravidade-100.png"))); // NOI18N
        jbPlaneta.setBorder(null);
        jbPlaneta.addActionListener(this::jbPlanetaActionPerformed);
        getContentPane().add(jbPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 100, -1));

        jbCalculadora.setBackground(new java.awt.Color(0, 0, 0));
        jbCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CalculadoraGreen.png"))); // NOI18N
        jbCalculadora.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbCalculadora.addActionListener(this::jbCalculadoraActionPerformed);
        getContentPane().add(jbCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        jbTriangulo.setBackground(new java.awt.Color(0, 0, 0));
        jbTriangulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/triangulopng.png"))); // NOI18N
        jbTriangulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbTriangulo.addActionListener(this::jbTrianguloActionPerformed);
        getContentPane().add(jbTriangulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Best Animations.gif"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 460));

        jMenu1.setText("Formularios");

        jMenuItem1.setText("Calculadora");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Lados Triangulos");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Gravidade");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Cadastrar");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Sair");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Calculadora c = new Calculadora();
        c.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Pitagoras p = new Pitagoras();
        p.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCalculadoraActionPerformed
        Calculadora c = new Calculadora();
        c.setVisible(true);
    }//GEN-LAST:event_jbCalculadoraActionPerformed

    private void jbTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTrianguloActionPerformed
        Pitagoras p = new Pitagoras();
        p.setVisible(true);
    }//GEN-LAST:event_jbTrianguloActionPerformed

    private void jbPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPlanetaActionPerformed
        GravidadePeso g = new GravidadePeso();
        g.setVisible(true);
    }//GEN-LAST:event_jbPlanetaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CadastroFuncionarios f = new CadastroFuncionarios();
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadastroFuncionarios f = new CadastroFuncionarios();
        f.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        GravidadePeso g = new GravidadePeso();
        g.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JButton jbCalculadora;
    private javax.swing.JButton jbPlaneta;
    private javax.swing.JButton jbTriangulo;
    // End of variables declaration//GEN-END:variables
}
