/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacevisual;

import javax.swing.JOptionPane;

/**
 *
 * @author 1094260
 */
public class Pitagoras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pitagoras.class.getName());

    /**
     * Creates new form Pitagoras
     */
    public Pitagoras() {
        initComponents();
    }
    public void calculo(){
        try {
            double l1 = Double.parseDouble(txfLado1.getText());
            double l2 = Double.parseDouble(txfLado2.getText());
            double l3 = Double.parseDouble(txfLado3.getText());

            if (l1==l2&&l2==l3) {
                jlbResultado.setText("Tipo: Equilátero");
            }else if(l1==l2||l2==l3||l3==l1){
                jlbResultado.setText("Tipo: Isósceles");
            }else if(l1!=l2&&l2!=l3){
                jlbResultado.setText("Tipo: Escaleno");
            }else{
                JOptionPane.showMessageDialog(null, "Error: Entrada Invalida!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!");
            throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfLado1 = new javax.swing.JTextField();
        txfLado2 = new javax.swing.JTextField();
        txfLado3 = new javax.swing.JTextField();
        jbVerificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jlbResultado = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pitagoras");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("Lado 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 38, -1, -1));

        jLabel2.setForeground(new java.awt.Color(153, 255, 0));
        jLabel2.setText("Lado 2:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 93, -1, -1));

        jLabel3.setForeground(new java.awt.Color(153, 255, 0));
        jLabel3.setText("Lado 3:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 151, -1, -1));

        txfLado1.addActionListener(this::txfLado1ActionPerformed);
        jPanel1.add(txfLado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 35, 143, -1));

        txfLado2.addActionListener(this::txfLado2ActionPerformed);
        jPanel1.add(txfLado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 90, 143, -1));

        txfLado3.addActionListener(this::txfLado3ActionPerformed);
        jPanel1.add(txfLado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 148, 143, -1));

        jbVerificar.setBackground(new java.awt.Color(153, 255, 0));
        jbVerificar.setForeground(new java.awt.Color(0, 0, 0));
        jbVerificar.setText("Verificar Tipo");
        jbVerificar.addActionListener(this::jbVerificarActionPerformed);
        jPanel1.add(jbVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 188, 208, -1));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 90, -1, -1));

        jlbResultado.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 1, 18)); // NOI18N
        jlbResultado.setForeground(new java.awt.Color(153, 255, 0));
        jlbResultado.setText("      TIPO");
        jPanel1.add(jlbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 91, 154, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/PitagorasJuniorFull.gif"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 110, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txfLado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLado2ActionPerformed

    private void txfLado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLado3ActionPerformed

    private void txfLado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLado1ActionPerformed

    private void jbVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerificarActionPerformed
        calculo();
    }//GEN-LAST:event_jbVerificarActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        try {
            java.awt.Desktop.getDesktop().browse(new java.net.URI("https://senacminas-my.sharepoint.com/:i:/g/personal/ptr11053_mg_senac_br/IQCS2_d7uvMXT42z27LIChQBAYtmdcaf4eC10aT0Itldcss?e=NfyaQs"));
        } catch (Exception e) {
            e.printStackTrace();
    }
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pitagoras().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbVerificar;
    private javax.swing.JLabel jlbResultado;
    private javax.swing.JTextField txfLado1;
    private javax.swing.JTextField txfLado2;
    private javax.swing.JTextField txfLado3;
    // End of variables declaration//GEN-END:variables
}
